services:
  wordpress:
    image: wordpress:latest
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: ""
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./:/var/www/html
      - ${HOME}/.hull/system/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      caddy: {{SITE_NAME}}.{{TLD}}
      caddy.reverse_proxy: "{{upstreams 80}}"
      caddy.tls: internal
    networks:
      - default
      - caddy

networks:
  caddy:
    external: true