services:
  app:
    image: serversideup/php:8.3-fpm-nginx
    volumes:
      - ./:/var/www/html
      - ${HOME}/.hull/system/php/xdebug.ini:/usr/local/etc/php/conf.d/99-xdebug.ini:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      caddy: {{SITE_NAME}}.{{TLD}}
      caddy.reverse_proxy: "{{upstreams 8080}}"
      caddy.tls: internal
    networks:
      - default
      - caddy

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: laravel
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - default
      - caddy

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    networks:
      - default

networks:
  caddy:
    external: true

volumes:
  db_data:
  redis_data:
