#!/bin/bash
set -euo pipefail

export APP_DIR="${APP_DIR:-$HOME/.hull}"

if [[ -f "compose.yaml" || -f "docker-compose.yml" ]]; then
    docker compose restart
else
    cd "$APP_DIR/system/caddy"
    docker compose restart
    echo "Global router and Adminer restarted."
fi
