package compose

import (
	"bytes"

	"gopkg.in/yaml.v3"
)

// File is the subset of the compose specification Hull generates.
// Environment and labels use list form ("KEY=value") so every value is an
// unambiguous YAML string and ordering is fully deterministic.
type File struct {
	Name     string                 `yaml:"name"`
	Services map[string]*ServiceDef `yaml:"services"`
	Networks map[string]*Network    `yaml:"networks,omitempty"`
	Volumes  map[string]*Volume     `yaml:"volumes,omitempty"`
}

// ServiceDef is one compose service.
type ServiceDef struct {
	Image         string               `yaml:"image,omitempty"`
	Build         string               `yaml:"build,omitempty"`
	ContainerName string               `yaml:"container_name,omitempty"`
	User          string               `yaml:"user,omitempty"`
	Entrypoint    []string             `yaml:"entrypoint,omitempty"`
	Command       string               `yaml:"command,omitempty"`
	Environment   []string             `yaml:"environment,omitempty"`
	Volumes       []string             `yaml:"volumes,omitempty"`
	Ports         []string             `yaml:"ports,omitempty"`
	ExtraHosts    []string             `yaml:"extra_hosts,omitempty"`
	Labels        []string             `yaml:"labels,omitempty"`
	Networks      []string             `yaml:"networks,omitempty"`
	HealthCheck   *HealthCheck         `yaml:"healthcheck,omitempty"`
	DependsOn     map[string]DependsOn `yaml:"depends_on,omitempty"`
}

// HealthCheck is a compose service healthcheck. Hull emits one on dedicated
// database services so a dependent app can wait on condition: service_healthy.
type HealthCheck struct {
	Test        []string `yaml:"test,omitempty"`
	Interval    string   `yaml:"interval,omitempty"`
	Timeout     string   `yaml:"timeout,omitempty"`
	Retries     int      `yaml:"retries,omitempty"`
	StartPeriod string   `yaml:"start_period,omitempty"`
}

// DependsOn is the long-form compose dependency condition (e.g. an app waiting
// for its database to be service_healthy before it starts).
type DependsOn struct {
	Condition string `yaml:"condition"`
}

// Network is a compose network definition.
type Network struct {
	External bool `yaml:"external,omitempty"`
}

// Volume is a compose named-volume definition (Hull only uses defaults).
type Volume struct{}

const header = "# Generated by Hull from hull.yaml , do not edit directly.\n# Regenerate with: hull render\n"

// Marshal renders the compose file as YAML with Hull's generated-file header.
func Marshal(f *File) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString(header)
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(f); err != nil {
		return nil, err
	}
	if err := enc.Close(); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
