package compose

import (
	"bytes"

	"gopkg.in/yaml.v3"
)

// File is the subset of the compose specification Hull generates.
// Environment and labels use list form ("KEY=value") so every value is an
// unambiguous YAML string and ordering is fully deterministic.
type File struct {
	Name     string                 `yaml:"name"`
	Services map[string]*ServiceDef `yaml:"services"`
	Networks map[string]*Network    `yaml:"networks,omitempty"`
	Volumes  map[string]*Volume     `yaml:"volumes,omitempty"`
}

// ServiceDef is one compose service.
type ServiceDef struct {
	Image         string   `yaml:"image,omitempty"`
	Build         string   `yaml:"build,omitempty"`
	ContainerName string   `yaml:"container_name,omitempty"`
	Command       string   `yaml:"command,omitempty"`
	Environment   []string `yaml:"environment,omitempty"`
	Volumes       []string `yaml:"volumes,omitempty"`
	Ports         []string `yaml:"ports,omitempty"`
	ExtraHosts    []string `yaml:"extra_hosts,omitempty"`
	Labels        []string `yaml:"labels,omitempty"`
	Networks      []string `yaml:"networks,omitempty"`
}

// Network is a compose network definition.
type Network struct {
	External bool `yaml:"external,omitempty"`
}

// Volume is a compose named-volume definition (Hull only uses defaults).
type Volume struct{}

const header = "# Generated by Hull from hull.yaml — do not edit directly.\n# Regenerate with: hull render\n"

// Marshal renders the compose file as YAML with Hull's generated-file header.
func Marshal(f *File) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString(header)
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(f); err != nil {
		return nil, err
	}
	if err := enc.Close(); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
