package engine

import (
	"fmt"
	"hash/fnv"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/CavenRE/hull/internal/manifest"
	"github.com/CavenRE/hull/internal/state"
)

// IngressServiceName is the compose service Hull injects to front a cluster in
// ingress: delegate mode.
const IngressServiceName = "hull-ingress"

// ingressOverlayFile / ingressCaddyFile are written into the compose root.
const (
	ingressOverlayFile = "compose.hull.yaml"
	ingressCaddyFile   = "compose.hull.caddy"
)

// IngressArtifacts is the generated pair for a cluster's ingress container: a
// compose overlay (added as an extra -f) and the Caddy config it mounts.
type IngressArtifacts struct {
	Overlay   []byte
	Caddyfile string
	BindIP    string
	Networks  []string
	Hosts     []string
}

// ClusterIngress builds the ingress-container artifacts for a cluster: a
// reverse proxy attached to every cluster network (so it can reach internal-only
// services by name), publishing 80/443 on a per-cluster loopback IP, with a
// network alias per routed hostname so in-network server-side calls resolve to
// it. It does not touch disk; callers preview or write the result.
func (e *Engine) ClusterIngress(p *state.Project) (*IngressArtifacts, error) {
	m := p.Manifest
	if m == nil || m.Type != manifest.TypeCluster {
		return nil, fmt.Errorf("%s is not a cluster", p.Name)
	}
	composeDir := filepath.Join(p.Dir, m.ComposeRoot)
	networks := readClusterNetworks(composeDir, m.ComposeFiles)
	if len(networks) == 0 {
		return nil, fmt.Errorf("cluster %s declares no networks for the ingress to join (delegate ingress needs the compose to define networks)", m.Name)
	}
	suffix := m.ClusterSuffix(e.Config.TLD)
	hosts := clusterHosts(m, suffix)
	if len(hosts) == 0 {
		return nil, fmt.Errorf("cluster %s has no served routes; assign one with `hull cluster route add`", m.Name)
	}
	bindIP := clusterLoopback(m.Name, e.Config.Router.Loopback)

	overlay, err := ingressOverlay(m.Name, networks, hosts, bindIP)
	if err != nil {
		return nil, err
	}
	return &IngressArtifacts{
		Overlay:   overlay,
		Caddyfile: ingressCaddyfile(m, suffix),
		BindIP:    bindIP,
		Networks:  networks,
		Hosts:     hosts,
	}, nil
}

// WriteClusterIngress writes the overlay + Caddyfile into the compose root, so
// the cluster can be started with the extra -f file.
func (e *Engine) WriteClusterIngress(p *state.Project, art *IngressArtifacts) error {
	composeDir := filepath.Join(p.Dir, p.Manifest.ComposeRoot)
	if err := os.WriteFile(filepath.Join(composeDir, ingressOverlayFile), art.Overlay, 0o644); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(composeDir, ingressCaddyFile), []byte(art.Caddyfile), 0o644)
}

// clusterHosts is the sorted, de-duplicated set of served hostnames.
func clusterHosts(m *manifest.Manifest, suffix string) []string {
	seen := map[string]bool{}
	var hosts []string
	for _, key := range m.RouteKeys() {
		rt := m.Routes[key]
		if !rt.Served() {
			continue
		}
		for _, h := range rt.Hosts(suffix) {
			if !seen[h] {
				seen[h] = true
				hosts = append(hosts, h)
			}
		}
	}
	sort.Strings(hosts)
	return hosts
}

// ingressCaddyfile renders the Caddy config the ingress container serves: one
// vhost per routed hostname, reverse-proxying to the compose service by name
// (reachable because the ingress shares the cluster networks, so internal-only
// services work too). TLS is Caddy's internal CA inside the container.
func ingressCaddyfile(m *manifest.Manifest, suffix string) string {
	var b strings.Builder
	b.WriteString("# Generated by Hull , do not edit (regenerated on `hull up`).\n")
	b.WriteString("{\n\tauto_https disable_redirects\n}\n\n")
	for _, key := range m.RouteKeys() {
		rt := m.Routes[key]
		if !rt.Served() {
			continue
		}
		for _, host := range rt.Hosts(suffix) {
			fmt.Fprintf(&b, "%s {\n\ttls internal\n\treverse_proxy %s:%d {\n\t\theader_up X-Forwarded-Proto https\n\t}\n}\n\n", host, rt.Service, rt.Port)
		}
	}
	return b.String()
}

// ingressOverlay renders the compose.hull.yaml overlay that adds the ingress
// service to a cluster. The cluster's networks are declared in its base compose,
// so the overlay only references them (compose merges the two -f files); each is
// given a per-hostname alias so in-network calls to the public names resolve to
// the ingress.
func ingressOverlay(name string, networks, hosts []string, bindIP string) ([]byte, error) {
	nets := map[string]any{}
	for _, n := range networks {
		nets[n] = map[string]any{"aliases": append([]string(nil), hosts...)}
	}
	svc := map[string]any{
		"image":          "caddy:2-alpine",
		"container_name": "hull-ingress-" + name,
		"restart":        "unless-stopped",
		"networks":       nets,
		"ports": []string{
			bindIP + ":80:80",
			bindIP + ":443:443",
		},
		"volumes": []string{
			"./" + ingressCaddyFile + ":/etc/caddy/Caddyfile:ro",
		},
	}
	doc := map[string]any{
		"services": map[string]any{IngressServiceName: svc},
	}
	var buf strings.Builder
	buf.WriteString("# Generated by Hull , the cluster ingress overlay. Do not edit.\n")
	buf.WriteString("# Run with the base compose: docker compose -f <base> -f " + ingressOverlayFile + " up -d\n")
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(doc); err != nil {
		return nil, err
	}
	_ = enc.Close()
	return []byte(buf.String()), nil
}

// clusterLoopback picks a deterministic 127.0.0.x bind IP for a cluster's
// ingress, distinct from Hull's own router loopback and from 127.0.0.1. This is
// a preview-grade allocation (hash-based); a live implementation would track
// used octets to guarantee no collision between two running clusters.
func clusterLoopback(name, hullLoopback string) string {
	h := fnv.New32a()
	_, _ = h.Write([]byte(name))
	octet := int(h.Sum32()%252) + 2 // 2..253
	ip := fmt.Sprintf("127.0.0.%d", octet)
	if ip == hullLoopback || ip == "127.0.0.1" {
		octet++
		if octet > 253 {
			octet = 2
		}
		ip = fmt.Sprintf("127.0.0.%d", octet)
	}
	return ip
}

// readClusterNetworks returns the network keys declared in a cluster's compose
// file (best-effort; nil when the compose is missing or unparseable).
func readClusterNetworks(composeDir string, files []string) []string {
	path := firstComposeFile(composeDir, files)
	if path == "" {
		return nil
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return nil
	}
	var doc struct {
		Networks map[string]yaml.Node `yaml:"networks"`
	}
	if err := yaml.Unmarshal(data, &doc); err != nil || len(doc.Networks) == 0 {
		return nil
	}
	names := make([]string, 0, len(doc.Networks))
	for n := range doc.Networks {
		names = append(names, n)
	}
	sort.Strings(names)
	return names
}
