package engine

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/CavenRE/hull/internal/manifest"
	"github.com/CavenRE/hull/internal/state"
)

const legacyCompose = `services:
  app:
    image: serversideup/php:8.1-fpm-nginx
    labels:
      caddy: oldshop.test
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: oldshop_db
`

func TestMigrateV1(t *testing.T) {
	e, root := testEngine(t)
	dir := filepath.Join(root, "oldshop")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "compose.yaml"), []byte(legacyCompose), 0o644); err != nil {
		t.Fatal(err)
	}

	p, err := state.Find([]string{root}, "oldshop")
	if err != nil {
		t.Fatal(err)
	}
	if !p.Legacy {
		t.Fatal("fixture should be detected as legacy")
	}

	m, err := e.MigrateV1(p)
	if err != nil {
		t.Fatal(err)
	}
	if m.Template != "laravel" || m.PHP != "8.1" {
		t.Errorf("manifest = %+v", m)
	}
	if m.Services["db"].Engine != "mysql" || m.Services["db"].Database != "oldshop_db" {
		t.Errorf("db = %+v", m.Services["db"])
	}

	if _, err := os.Stat(filepath.Join(dir, "compose.yaml.v1-backup")); err != nil {
		t.Error("legacy compose not backed up")
	}
	if _, err := manifest.Load(dir); err != nil {
		t.Errorf("written hull.yaml invalid: %v", err)
	}
	data, _ := os.ReadFile(filepath.Join(dir, "compose.yaml"))
	if !strings.Contains(string(data), "Generated by Hull") {
		t.Error("compose.yaml not regenerated")
	}

	// Re-running must refuse (already adopted).
	p2, err := state.Find([]string{root}, "oldshop")
	if err != nil {
		t.Fatal(err)
	}
	if _, err := e.MigrateV1(p2); err == nil {
		t.Error("second migrate should fail")
	}
}
